packages:
  - apps/*
  - packages/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  sharp: false

overrides:
  sharp: 0.35.3

minimumReleaseAgeExclude:
  - '@angular-devkit/architect@0.2200.7'
  - '@angular-devkit/build-angular@22.0.7'
  - '@angular-devkit/build-webpack@0.2200.7'
  - '@angular-devkit/core@22.0.7'
  - '@angular-devkit/schematics@22.0.7'
  - '@angular/animations@22.0.7'
  - '@angular/build@22.0.7'
  - '@angular/cli@22.0.7'
  - '@angular/common@22.0.7'
  - '@angular/compiler-cli@22.0.7'
  - '@angular/compiler@22.0.7'
  - '@angular/core@22.0.7'
  - '@angular/forms@22.0.7'
  - '@angular/language-service@22.0.7'
  - '@angular/platform-browser-dynamic@22.0.7'
  - '@angular/platform-browser@22.0.7'
  - '@angular/router@22.0.7'
  - '@ionic/angular@8.8.14'
  - '@ionic/core@8.8.14'
  - '@ngtools/webpack@22.0.7'
  - '@schematics/angular@22.0.7'

onlyBuiltDependencies:
  - sharp
