apply plugin: 'com.android.library'

android {
    namespace = "com.sheldrapps.plugins.epubrewrite"
    compileSdk = rootProject.ext.compileSdkVersion

    testOptions {
        unitTests.returnDefaultValues = true
    }

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
    }

    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs_nio:2.1.5'
    implementation project(':capacitor-android')
    implementation 'androidx.activity:activity:1.9.3'
    implementation 'org.apache.commons:commons-compress:1.28.0'
    implementation 'net.lingala.zip4j:zip4j:2.11.5'
    testImplementation 'junit:junit:4.13.2'
}
